### ISSUE TITLE
Sort comments

### ISSUE THREAD

**Issue by satish9323** [WP-API/node-wpapi#188]
Hi, 

Is it possible to sort the comments as I want latest comment first ?? I tried .filter() and its not working.

**Comment by kadamwhite** [comment]
You should be able to do this with `.param( 'order', 'desc' )` (as opposed to 'asc', ascending). The [comments collection supports](http://v2.wp-api.org/reference/comments/) (see "list comments" section) both `order` (asc or desc, for ascending or descending) and `orderby` if you want to order by something other than date_gmt.

That said, I suggest [opening an issue on the main WP-API repository](https://github.com/WP-API/WP-API/issues/new) to see whether the default ordering of ascending is intentional: given that we show posts e.g. most-recent first, it's odd that comments work differently.
