### ISSUE TITLE
Multiple dynamic properties in endpoint

### ISSUE THREAD

**Issue by joneslloyd** [WP-API/node-wpapi#198]
Hi there,

I'm trying to do something like this:

```
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

var site = new WP({
  endpoint: window.MyVars.site_url + '/wp-json',
  nonce: window.MyVars.nonce
});

site.mySiteDel = site.registerRoute( 'myapp/v1', '/delete_title_uid/(?P<id>\\d+)/(?P<titleUid>\\d+)' );

site.mySiteDel().id( window.MyVars.current_post_id ).titleUid( toDelete ).delete().then(( data ) => {

  //SUCCESS
  return null;
}).catch(( err ) => {

  console.log( err );
  //FAIL
});
```

Where I have a post (signified by ID), and a piece of meta, which (due to being stored in an array) has its own ID, labelled here as a "Title UID".

When I try the above code, I get the JS console error:
```
Uncaught TypeError: n.mySiteDel(...).id(...).titleUid is not a function
```

On the PHP side of things, I have an endpoint registered like so:
```
register_rest_route( 'myapp/v1', '/delete_title_uid/(?P<id>\d+)/(?P<titleUid>\d+)', array(
			'methods' => 'DELETE',
			'callback' => array( $this, 'delete_func' ),
		) );
```

Do you know what could be up?

**Comment by kadamwhite** [comment]
Nope, but I will investigate!

**Comment by joneslloyd** [comment]
Thanks a lot! Super project by the way. This issue is the one current bug in the way of me completing my integration :)

**Comment by kadamwhite** [comment]
@joneslloyd Thanks! Looks like the issue is that the library assumes a `snake_case` parameter identifier, not a `camelCase` identifier -- so `titleUid` is tripping up the system, because the token is lowercased when creating the method name and therefore gets assigned as `titleuid` instead.

One unrelated (and totally unsolicited) comment I might make about your URL scheme is that it looks like you're using our URL to define the action to be taken -- deleting a title by UID -- rather than using the URL to reference a resource and using the DELETE http action on that resource. Depending on what you're actually deleting, there may be a more strictly-RESTful way to describe your routes.

Thanks a ton for the bug report, fix incoming soon!

**Comment by kadamwhite** [comment]
If you `npm install wpapi@beta` this should now be working as you expect—please re-open the issue if not. Much obliged for the bug report, and thanks for using the library!

**Comment by joneslloyd** [comment]
Ah-ha! Got it! I'll do just that and let you know if not working :)

You're right re: My nomenclature on the URLs - I need to change that.

Thanks again, and I'll let you know if & when I find anything.

Over & out!
