### ISSUE TITLE
Custom routes POST Request

### ISSUE THREAD

**Issue by pvlvsk** [WP-API/node-wpapi#244]
Hi,

i've set up a custom route for creating new menu items via the WP REST API. In Postman it works flawlessly but i can't get it to work with this package. The question is how i make a POST request with a custom route? Here is my code so far:

```
let wp = new WPAPI({
          endpoint: 'http://xxxxxx',
          username: 'xxxxx',
          password: 'xxxxx'
      });
      wp.menuAPI = wp.registerRoute( 'wp-api-menus/v2', '/create-item/id=(?P<id>)');

      wp.menuAPI().id(4).then(function( response ) {
          console.log( response );
      });
```

This makes a GET request, I need POST instead...

Thank you!

**Comment by kadamwhite** [comment]
@pvlvsk Thanks for using `node-wpapi`! All the same rules about [creating records](http://wp-api.org/node-wpapi/using-the-client/#creating-posts) apply to custom endpoints as do to the built-in collections; one of those rules is that `.then` is an alias for `.get().then` unless another promise-returning request method is called.

In this case, I suspect that
```js
wp.menuAPI().id(4).create({
  data: 'for',
  your: 'POST request'
}).then(function( response ) {
```
will get you what you want; if you're looking to update the record at ID 4, you'd use `.update` instead of `.create`.

Let me know if that resolves the problem, and if it does, I'd welcome input on how to improve the documentation here

**Comment by pvlvsk** [comment]
Yes! It's working now! Thank you very much!

**Comment by kadamwhite** [comment]
Our pleasure! Glad to hear things are working.
