### ISSUE TITLE
create post in CPT

### ISSUE THREAD

**Issue by parsafatehi** [WP-API/node-wpapi#277]
Is it possible to create post in a custom post type with wp.posts or wp.types?

**Comment by bigandy** [comment]
Yes. I had the same problem and here's how I did it. 

- In WordPress cpt code make sure `'show_in_rest' => true` [see my code](https://github.com/bigandy/big-andy.co.uk/blob/live/content/plugins/bigandy/cpts.php#L32) with my 'health' cpt it gives me an endpoint of `site-url/wp-json/wp/v2/health` 

- in your wpapi code: 
wp.health = wp.registerRoute('wp/v2', '/health/(?P<id>\\d+)');
wp.health().create({})... // create a health record
[take a look at my code](https://github.com/bigandy/wpapi/blob/master/create-health.js#L20)

**Comment by parsafatehi** [comment]
@bigandy It works. 
Thanks

**Comment by kadamwhite** [comment]
@parsafatehi Glad to hear things are sorted! There's also some [documentation around working with CPTs](http://wp-api.org/node-wpapi/custom-routes/) in this library's docs, and I'd welcome suggestions on how to make them easier to find.

One note: You'll need to use `\\` (double-backslashes) in the regex that @bigandy shared above, like this:
```
wp.health = wp.registerRoute('wp/v2', '/health/(?P\\d+)');
```
Otherwise the string will be misinterpreted in JavaScript
