### ISSUE TITLE
posts() not working

### ISSUE THREAD

**Issue by nezzard** [WP-API/node-wpapi#278]
Hi, i try to get posts by 
wp.posts() or wp.posts().id(1)
But nothing return

When i try to create posts, all works, but not get 
`EndpointRequest {
  _options: 
   { auth: true,
     endpoint: 'http://xxxxx/wp-json/',
     username: 'xxxx',
     password: 'xxxx' },
  transport: {},
  _params: {},
  _supportedMethods: [ 'get', 'post', 'put', 'patch', 'delete', 'head' ],
  _path: { '0': 'posts', '1': 1 },
  _levels: 
   { '0': [ [Object] ],
     '1': [ [Object] ],
     '2': [ [Object] ],
     '3': [ [Object] ] },
  _namespace: 'wp/v2' }
`

**Comment by kadamwhite** [comment]
Hello @nezzard and thanks for using this library. In order to send a request, you need to use one of the request terminator methods -- `.create()`, `.update()`, `.delete()`, or in this case, `.get()` or `.then()` (which aliases to `.get().then` internally). So, to GET posts:
```js
wp.posts().then(function( posts ) {
  // "posts" is an array of recent posts
})
```
or explicitly using `.get()`,
```js
wp.posts().get().then(function( posts ) {
  // "posts" is an array of recent posts
})
```
You can check out the [integration tests](https://github.com/WP-API/node-wpapi/blob/master/tests/integration/posts.js) for examples of these methods in action.

Hope this helps!
