### ISSUE TITLE
.pages().slug('foo').update error - `rest_no_route`

### ISSUE THREAD

**Issue by benfoxall** [WP-API/node-wpapi#301]
Hey @kadamwhite - this is the issue that I mentioned yesterday.

I expected to be able update the content of a page with this:

```js
wp.pages().slug('my-page').update({content: 'new content'})
```

But it looked like `.update` wasn't a function.  I ended up using a [pretty ugly work around](https://github.com/benfoxall/mqtt-wp/blob/master/bridge.js#L18-L20) - though I'd love to know how to remove it.

There's a good chance I'm doing this wrong!

**Comment by kadamwhite** [comment]
Something's definitely going wrong here, because that method exists in a reduced test case I put together. @benfoxall Can you clarify how the `wp` object is being created? Are you using auto-discovery, or the out-of-the-box `new WPAPI()`?

**Comment by kadamwhite** [comment]
@benfoxall Also, what version of the library are you using?

**Comment by benfoxall** [comment]
I'm creating the client with `new WPAPI()` with endpoint/username/password properties (using the basic-auth plugin).  I went down the manual route because I was trying to get this to work with wordpress.com originally.

I'm using version [1.0.2](https://github.com/benfoxall/mqtt-wp/blob/master/yarn.lock#L662-L664).

I'll be revisiting this code tomorrow, I can try updating to 1.0.3 & using auto-discovery.

**Comment by benfoxall** [comment]
Apologies - I had the error wrong. It's not function undefined - the promise fails with the following:

```js
{
  code: 'rest_no_route',
  message: 'No route was found matching the URL and request method',
  data: { status: 404 }
}
```

I've uploaded a [test case](https://github.com/benfoxall/mqtt-wp/blob/4c478bc5fb12871dac02125f48241339d2b1e961/test-case.js) to my repo.  I'm going to try and update the library and use auto-discovery now

**Comment by benfoxall** [comment]
I've updated to 1.0.3 and [updated my test case to use auto-discovery](https://github.com/benfoxall/mqtt-wp/blob/38a6c333620da5668919a3652967bdbb8fb208a2/test-case.js). And I still get the same 404 error response.

**Comment by kadamwhite** [comment]
d'oh, I figured it out; sorry for the delay, I was chasing the wrong problem. `.slug()` is working correctly, but the result of any _search operation_ (and searching by slug counts) is an array of posts, not a post object. So, to update this resource, you'd need to make two hops:

```js
	.then(wp =>
		wp.pages()
			.slug('my-thing')
			.then((pages) => {
				// pages will be an array of length 1
				if (!pages.length) {
					throw new Error('no page found for that slug');
				}
				return pages[0];
			}).then(page =>
				wp.pages()
					.id(page.id)
					.update({content: 'This is test content'})
			)
			.then(
				() => console.log('Completed'),
				e  => console.error(e)
			)
	);
```
The critical part is to read out the ID of the post from the returned array containing the match for the provided slug, because that post object is where you're going to find the ID you need to make the `update` (PUT) request. The URLs that can be used to uniquely address pages all depend on ID.

**Comment by kadamwhite** [comment]
I'm going to close this out because it does look like things are working as they must given the structure of the REST API, but if there's a specific improvement you'd like to see made to the docs to prevent this type of issue please suggest it and I'll re-open the ticket to cover implementing that docs fix. Sorry for the delay, @benfoxall, and thank you again for raising the issue.
