### ISSUE TITLE
How to apply Filter to Custom Post Types Routes

### ISSUE THREAD

**Issue by arvindkumarbadwal** [WP-API/node-wpapi#302]
Is there anyway to apply filter parameter to custom post type?

For example: 

```javascript
var site = new WP({ endpoint: 'http://www.yoursite.com/wp-json' });
site.myCustomResource = site.registerRoute( 'myplugin/v1', '/author' );
```

and i want to apply  filter like => `filter[orderby]=menu_order`  and `order=desc`.

How i can perform such operation using custom routes?

**Comment by kadamwhite** [comment]
@arvindkumarbadwal `?order` and `?orderby` are both supported for all endpoints without the use of `filter` -- these are both [native pagination parameters supported by REST API collections](https://developer.wordpress.org/rest-api/using-the-rest-api/pagination/).

Because these are built-in, no additional work should be needed, and you should be able to do:

```js
var site = new WP({ endpoint: 'http://www.yoursite.com/wp-json' });
site.myCustomResource = site.registerRoute( 'myplugin/v1', '/author' );
site.myCustomResource().orderby('menu_order').order('desc')...
```
Should you wish to use filter, you would [apply it like any other custom route mixin](http://wp-api.org/node-wpapi/custom-routes/), by including a configuration object when registering the route:
```js
site.myCustomResource = site.registerRoute( 'myplugin/v1', 'collection/(?P<id>)', {
    // Support the .filter( 'filter_key', 'filter_value' ) chaining method
    params: [ 'filter' ]
});
```
I hope this helps, please leave a comment here if this does not address your issue!
