### ISSUE TITLE
Automatic OPTION request to the endpoint before my Gets. 

### ISSUE THREAD

**Issue by arturgithub** [WP-API/node-wpapi#309]
Hello,

thank you for your amazing work and apologies if this is not the proper channel to address this issue.

I am using your project in a react application using:

- The "Create React App" boilerplate (hot reloading and all that stuff)
- Chrome as my browser with CORS add-on. 

The issue is that I have found that whenever I am performing a GET request to my custom endpoint using the your standard way: 

- new WPAPI({});  ...
- Basic Aunthentication

there is an OPTIONS request to my custom endpoint (before the actual GET one) that last longer than the actual GET request... Is this they way it works??

Thanks very much for your response!!!

**Comment by kadamwhite** [comment]
Thanks for the kind words, and for using this library!

What you are describing is a result of the way CORS requests get handled by the browser. The OPTIONS request happens automatically when making a cross-origin call that counts as a [Preflighted request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests); it's part of the CORS specification, and outside of our control (because it's something that happens at the browser level).

However, according to the CORS specification, GET requests specifically would _sometimes_ count as "[Simple Requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#application/json)" if certain conditions are met -- unfortunately those conditions include the following caveat,

> The only allowed values for the Content-Type header are:
> - application/x-www-form-urlencoded
> - multipart/form-data
> - text/plain

Because Superagent (and therefore this library) assumes a content-type of `application/json`, this does not trigger the "simple request" and therefore _does_ trigger the OPTIONS call.

It would be possible to patch the HTTP transport within this library to preference multi-part form data for GET requests, but that is not the direction we want to go with the library as a whole so I'm afraid you'd be on your own for that implementation (though I can point you at some resources if you need assistance). Again, even with patching the transport we'd only be able to skip the OPTIONS call for GET requests, because beyond that this is indeed the way it works.

Final thought: I'm surprised that the OPTIONS call takes so long to resolve; maybe this is something we could take to the main WP trac issue list to see if there's a performance bottleneck we can improve the performance at the WordPress level?

Since this doesn't appear to be something going wrong at the library level I am going to close this issue, but I'd welcome your continued discussion in this comment thread. Hope this helps!

**Comment by kadamwhite** [comment]
Linking this to #249 and #303 as it seems related

**Comment by arturgithub** [comment]
Thank you for your quick and comprehensive response!!

As in my case, it only affects my development environment, I can perfectly live with things working the way they currently do :)

I would try to gather some time to audit the OPTIONS and GET time responses and let you know.

Best regards,
