### ISSUE TITLE
Custom route doing HTTP POST request

### ISSUE THREAD

**Issue by entr** [WP-API/node-wpapi#311]
According #244 we should use `create(data)` promise in order to perform POST request but instead I'm seeing empty POST header and my `data` is sent as Request Payload. In my custom endpoint handler I see my `data` is being indeed found in request body. Is that the expected behavior or I'm missing something?

I'm trying to do simple login that mimics standard WP login process and acquire `logged_in` cookie this is `$data` (first arg) passed to php route callback:

```log
WP_REST_Request::__set_state(array(
   'method' => 'POST',
   'params' => 
  array (
    'URL' => 
    array (
    ),
    'GET' => 
    array (
    ),
    'POST' => 
    array (
    ),
    'FILES' => 
    array (
    ),
    'JSON' => 
    array (
      'username' => 'askl;djaksdj',
      'password' => 'as;ldkjqwe',
    ),
    'defaults' => 
    array (
    ),
  ),
   'headers' => 
  array (
    'accept_language' => 
    array (
      0 => 'bg,en-US;q=0.8,en;q=0.6',
    ),
    'accept_encoding' => 
    array (
      0 => 'gzip, deflate',
    ),
    'referer' => 
    array (
      0 => 'http://localhost:8080/',
    ),
    'dnt' => 
    array (
      0 => '1',
    ),
    'accept' => 
    array (
      0 => '*/*',
    ),
    'content_type' => 
    array (
      0 => 'application/json',
    ),
    'user_agent' => 
    array (
      0 => 'Mozilla/5.0 (Linux; Android 4.4.2; Nexus 4 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Mobile Safari/537.36',
    ),
    'origin' => 
    array (
      0 => 'http://localhost:8080',
    ),
    'cache_control' => 
    array (
      0 => 'no-cache',
    ),
    'pragma' => 
    array (
      0 => 'no-cache',
    ),
    'content_length' => 
    array (
      0 => '51',
    ),
    'connection' => 
    array (
      0 => 'keep-alive',
    ),
    'host' => 
    array (
      0 => 'wp.carpool.dev',
    ),
  ),
   'body' => '{"username":"askl;djaksdj","password":"as;ldkjqwe"}',
   'route' => '/profile/v1/login',
...
```

**Comment by kadamwhite** [comment]
Hello and thanks for using this library! I'm not sure from your description whether you're encountering an issue using node-wpapi, or clarifying how it functions. By default Superagent (and other HTTP libraries like Axios) will send JSON payloads as the request body, rather than form-encoded; I think this is what you are asking, if you can clarify I can explain further (or help to troubleshoot if you're having difficulty!)

**Comment by entr** [comment]
So it is safe to assume we can't send POST requests with WPAPI. Mostly I was wondering how to do it since POST is a valid route method that can be used in WP's `register_rest_route()`

**Comment by kadamwhite** [comment]
@entr sorry for the delayed follow-up on this. I'm still not sure I understand what you're having trouble with, because you can send a POST request with this library, and `register_rest_route` should accept POST requests dispatched with `create`. Nothing about GET or POST preclude having the data passed as a request body, that's based on the Content-Type and encoding used; in the API we're assuming the content-type `application/json` by default so the JSON body will be parsed if the request that is sent is a POST. There are a number of applications using this library which do use POST requests, along with JSON-encoded bodies of content-type application/json, and the requests get processed and stored in WordPress as expected.

You can alternatively use your own HTTP library (including standalone Superagent) to send a form-data-encoded POST request, but it shouldn't be necessary except for image uploads (which must be multi-part form encoded).

I'm going to close this out for now but add a comment below if you can clarify what you are trying to do, what you expect to happen and what is actually happening, and I may be able to help more
