### ISSUE TITLE
Post Request to Custom Post with Custom Fields

### ISSUE THREAD

**Issue by rotexhawk** [WP-API/node-wpapi#319]
I have created a custom post type in Wordpress and exposed it to rest API. I have also added custom fields to this post using the ACF plugin. 

In my themes function.php I have registered these fields in the response and I can see them when I make a get request. 
`register_rest_field('auto', 'specs', array('get_callback'  => 'get_autos_specs_for_api'));`

The problem is that when I send a post request, wordpress doesn't recognize these fields. It creates a new post with the title and all these fields are empty.

**Comment by juellez** [comment]
@rotexhawk have you tried this plugin to connect the ACF data w/the API? https://wordpress.org/plugins/acf-to-rest-api/

**Comment by kadamwhite** [comment]
@rotexhawk Looks like you probably need to give the `register_rest_field` options object an `update_callback` function; you're only defining the GET callback, so your endpoint doesn't know how to handle the received data when a POST or PUT is received. Check out the [`register_rest_field` documentation](https://developer.wordpress.org/reference/functions/register_rest_field/), or try out the referenced ACF to REST API plugin; both should help you achieve what you want!

I'm going to close this issue because it does not seem to represent a bug within the library code, but good luck sorting the problem out and thank you for using the REST API and this library.
