### ISSUE TITLE
Authenticating as administrator while logged in as subscriber

### ISSUE THREAD

**Issue by invisibled** [WP-API/node-wpapi#358]
Loving this package so far, it's been a breeze to use, but i'm running into an issue i can't quite solve.

I have an account section for users to manage some preferences on the frontend. The users are regular wordpress users with subscriber level access and they login using the standard wordpress login form. 

When a user is logged in and in their account section on the frontend, I initiate the WPAPI library and pass authentication with an admin account:
```
connect : () => new WPAPI({
    endpoint : self.getUrl(),
    username : config.wp.auth.user,
    password : config.wp.auth.pass,
    auth     : true
}),
```

I then call to get the data of the subscriber user
```
wpapi.wp.users().id(userID)
        .then( res => console.log(res))
        .catch( err => console.log(err))
```

which generates the following response
```
code:"rest_user_cannot_view"
data:{status: 401}
message:"Sorry, you are not allowed to list users."
```

however if I log out of all accounts (i've seen the issue where if you are logged in as an admin while making api calls it can fail) and navigate to the same page, the request works. It seems like when i am logged in as the subscriber, it's authenticating with that account instead.

Has anybody encountered this issue before or found a way around it? Let me know if you need any more info or if i haven't explained myself clear enough. Thanks!

**Comment by kadamwhite** [comment]
If you're using username & password, I am assuming you're using the Basic Authentication plugin? Cookie/nonce authentication (the most common auth scheme in client applications) is designed to authenticate requests using the credentials of the active logged-in user, so if you're using both, I believe the login cookie will "win".

As an aside, what you're describing (passing admin credentials into your JS app to trigger a privileged request from a subscriber login session) sounds like it would let a savvy user read or at minimum re-use the admin credentials for their own purposes. I would strongly recommend finding an alternative way to get the information you need, such as filtering the authentication check to permit listing users when the request is coming from a subscriber (probably best), or even creating a custom endpoint that subscribers could access, rather than leaking admin password strings into your front-end layer.
