### ISSUE TITLE
filter and meta query

### ISSUE THREAD

**Issue by jonesmorgan** [WP-API/node-wpapi#374]
Hey I hope all is well, thanks a lot for the pointers on the other issues, much appreciated!

Here is my WP-API object being initialised with the CPT:
```
import WPApi from "wpapi";

process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

const wp = new WPApi({
  endpoint: window.SITE.rest_url,
  nonce: window.SITE.nonce,
});

wp.vacancies = wp.registerRoute("wp/v2", "/vacancies/(?P<id>\\d+)", {
  params: ["filter"],
});

export default wp;
```

And here is how I use it (hard-coding the meta_value for testing’s sake) :

```
wp
      .vacancies()
      .filter({
        meta_key: "branch",
        meta_value: "Site Saudi Arabia",
      })
      .get()
```

And here is the API URL being hit, as per Chrome’s Netowork tab: `http://site.test/wp-json/wp/v2/vacancies?filter%5Bmeta_key%5D=branch&filter%5Bmeta_value%5D%5B%5D=Site%20Saudi%20Arabia`

Note that `meta_key` and `meta_value` are being applied as two separate filter paramters, rather than one. I think this could be the root cause of why it’s not working.

Do you know what I can do to make this work?

Cheers,

Morgan

**Comment by invisibled** [comment]
would love to know how to do this as well!

**Comment by joneslloyd** [comment]
Hey guys,

You have to install [this](https://github.com/WP-API/rest-filter) (or at least copy its code into your theme), _but_, make sure that you've modified it (as per the pull requests on the repo) so that this `$vars = apply_filters( 'query_vars', $wp->public_query_vars );` becomes this: `$vars = apply_filters( 'rest_query_vars', $wp->public_query_vars );`, and then add this right after the above modification:
```
function allow_meta_query( $valid_vars )
	{
	    $valid_vars = array_merge( $valid_vars, array( 'meta_query', 'meta_key', 'meta_value', 'meta_compare' ) );
	    return $valid_vars;
	}
	$vars = allow_meta_query( $vars );
```
It should now work with filtering posts / pages / CPTs.

(Note: If you have a CPT like in the case of this Issue, make sure it supports the `filter` param:
```
wp.vacancies = wp.registerRoute("wp/v2", "/vacancies/(?P<id>\\d+)", {
  params: ["filter"],
});
```

Then you can do things like:
```
let first_filter = $(".filter-form select.first-filter").val();
    let second_filter = $(".filter-form select.second-filter").val();
    let third_filter = $(".filter-form select.third-filter").val();

      let query = {
          relation: "AND",
      };

      if( 'any' !== first_filter ){
          query[0] = {
              key: "first",
                  value: first_filter,
          };
      }

      if( 'any' !== second_filter ){

          query[1] = {
              key: "second",
                  value: second_filter,
          };
      }

      if( 'any' !== third_filter ){
          query[2] = {
              key: "third",
              value: third_filter,
          };
      }
wp
      .my_cpts()
      .filter({
        meta_query: query,
      })
      .get()
      .then(my_cpts => {
        var my_cpt_data = [];
        for (let my_cpt_index in my_cpts) {
          if (my_cpt_index === "_paging") {
            continue;
          }
          let single_my_cpt = my_cpts[my_cpt_index];
          let my_cpt_html = getMyCptHtml(single_my_cpt);

          my_cpt_data.push(my_cpt_html);
        }
        return my_cpt_data;
      })
      .then(my_cpt_data => {
        $(".modules-layouts__all_my_cpts .container .my_cpts-output").html(
          my_cpt_data
        );
      });
```
(`any` is a hard-coded select option that tells the code to ignore that particular filter, as I've found that there isn't an actual value for a given meta key that can be passed which instructs the query to get all meta values for a given key).

**Comment by kadamwhite** [comment]
The referenced PR has been merged on the rest-filter repo; I'm going to provisionally close this out as it seems like it was a limitation on that side, and not this one. If that's inaccurate please feel free to open a new bug!
