### ISSUE TITLE
FindOrCreate

### ISSUE THREAD

**Issue by robertmylne** [WP-API/node-wpapi#375]
How can I write this query out:

```
    let category = await wp.categories().findOrCreate({
        name: 'test1'
    })
```

I want it to create the category if it exists, if not I want to return the existing category.

**Comment by kadamwhite** [comment]
I believe you'd have to chain multiple HTTP requests: This is untested code but it ought to look something like
```js
const findOrCreate = async ( categorySlug ) => {
	const matchingCats = await wp.categories().slug( categorySlug ).get();
	if ( matchingCats.length ) {
		return matchingCats[ 0 ];
	}
	return wp.categories().create( {
		name: categorySlug
	} );
};   
```
This may look a little more complex if you want to search on the category name vs the slug (you'd probably want to use `.search()` instead of `.slug()`, but I hope this'll get you started.

I'm going to close this issue as it represents a support inquiry rather than a bug with the library; however, if you feel there are any documentation changes that might make this more obvious (here or in the https://github.com/wp-api/docs WordPress REST API main documentation reposiory), we'd welcome the suggestion or a PR. Thanks!
