### ISSUE TITLE
`cannot POST /wp/v2/posts (404)`

### ISSUE THREAD

**Issue by eldyvoon** [WP-API/node-wpapi#395]
I can't create a post, I got error of `cannot POST /wp/v2/posts (404)`

My code is from the doc

```
var wp = new WPAPI({
    endpoint: 'https://example.com',
    username: 'ss',
    password: 'ssss'
  })

  wp
    .posts()
    .create({
      title: 'Your Post Title',
      content,
      status: 'publish'
    })
    .then(function(response) {
      // "response" will hold all properties of your newly-created post,
      // including the unique `id` the post was assigned on creation
      console.log('response id', response.id)
    })
    .catch(response => {
      console.log(response)
    })
```

I googled and most of the people recommendation were to turn off permalink, I did, but no effect. I have mod_rewrite by default is enabled.

**Comment by brionace** [comment]
Do you have /wp-json at the end of your endpoint url?

**Comment by eldyvoon** [comment]
Yeah

**Comment by kadamwhite** [comment]
@eldyvoon Based on your confirmation about the endpoint URL above, if your example reads
```
var wp = new WPAPI( { 
  endpoint: 'https://example.com/wp-json', // Note the "wp-json"
  username: 'ss',
  password: 'sss',
} );
```
and you still have this issue, then I'm not sure what the issue would be. I would expect an auth issue in that case. However, I do want to reconfirm that the above is true, because while you responded to the prior question by confirming that you had the wp-json string at the end of your endpoint URL, it did not appear in your original post.

Permalinks _must_ be enabled for this to work, unlike what you described; I'm not sure what your search was, but for the `/wp-json` endpoint to be accessible, some permalink scheme is required.

**Comment by kadamwhite** [comment]
I'm going to close this out due to lack of response. If you are still experiencing an issue, please leave a comment below with more information and we can continue the conversation. Thank you!
