### ISSUE TITLE
Maintaining order of post ids while querying post

### ISSUE THREAD

**Issue by mohit8935** [WP-API/node-wpapi#421]
Hi I have created a new parameter ids in my api and I am passing the array of ids like [595,598,594,555], I want the post to be retrieved in this order but when I am checking the response of ids in the wordpress backend I am receiving  the sorted array. Is there anyway I can prevent the array to be sorted so I can retrieve the post in the order I specified. In the custom query in my backend I have set 'orderby' as 'post__in' but as the array I am receiving is 'sorted' I am not able to maintain the order.

**Comment by kadamwhite** [comment]
From your comment "I have created a new parameter" I cannot tell if you are describing a custom endpoint; if so, you should be free to implement whatever parameters you want, and use `.param()` to set them.

To do what you describe on the posts endpoint, though:

```js
/wp-json/wp/v2/posts?include=2811,2478,2824&orderby=include
```
Or, in code:
```js
site.posts().include( [ 2811, 2478, 2824 ] ).orderby( 'include' )...
```
This will order the resulting collection by the IDs passed through in the `include` parameter.

**Comment by nsundberg** [comment]
> Or, in code:
> 
> ```js
> site.posts().include( [ 2811, 2478, 2824 ] ).orderby( 'include' )...
> ```
> 
> This will order the resulting collection by the IDs passed through in the `include` parameter.

@kadamwhite I believe this is actually not working. From what I can tell it is because of this sorting that happens here:
https://github.com/WP-API/node-wpapi/blob/f4a23a958007f5b7e7381e4fd70fa62b78470bdf/lib/constructors/wp-request.js#L403-L405

You currently need to call `toString()` on the array of IDs to bypass the sorting if you want to use `.orderby('include')` or similar.
