### ISSUE TITLE
How To Handle Request Time Out

### ISSUE THREAD

**Issue by dgard94** [WP-API/node-wpapi#441]
I want to add some error handler when the request is timeout, e.g if I make a request and get a response more then 10 seconds it will throw an error.

how to do that?

**Comment by kadamwhite** [comment]
The easiest way to do this would be as a wrapper at the parent application level, rather than modifying any specific behavior of this library itself, although you could also override the transport object directly. I could imagine you could use [`Promise.race`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race) for this:
```
function request( query ) {
  const timeout = new Promise( function( resolve, reject ) {
    setTimeout( reject, 10 * 1000 );
  } );
  return Promise.race( [
    query,
    timeout,
  ] );
}

request( site.posts().perPage( 100 ) )
```
Hope this helps! As it represents a "how-to" question rather than an issue with the library itself, I'm going to close it out, but please leave a question below if you need any further assistance.

**Comment by mangs** [comment]
I'm wondering the same thing. Superagent handles timeouts directly, so why not just piggyback on that? https://visionmedia.github.io/superagent/#timeouts

**Comment by fishsaidno** [comment]
Yeah I'm a little on the fence with the 'handle it the parent application level' advice too. The easiest way is certainly not always the best way. That said, I do see the benefit in having the developer create a wrapper around the WPAPI request, as they can implement their retry logic there as well.

There is a caveat. Using Promise.race or similar to affect the timeout by essentially 'forgetting' about the request & then retrying isn't ideal.
I admit I haven't taken a deep look at the transport layer code. But this would likely result in the 'forgotten' request's socket not being cleaned up. Which, depending on the parent applications architecture, could result in connection pool issues.

As @mangs noted, [superagent can handle this properly](https://visionmedia.github.io/superagent/#timeouts).

It'd be possible to expose an option in the WPAPI to allow the developer to pass timeout values through to the transport.
The default would be to keep the current behaviour - no timeouts - maintaining backwards compatibility.

Imho this would be great to have within the library itself.
Though I can understand the maintainer's desire to keep it simple too.

@kadamwhite Any extra thoughts?
