### ISSUE TITLE
How to set the permalink when creating a post?

### ISSUE THREAD

**Issue by IonicaBizau** [WP-API/node-wpapi#445]
What is the way to set the permalink (not the slug) when using `wp.pages().create` or `wp.posts.create`?

**Comment by kadamwhite** [comment]
The permalinks will be a result of the slug, which you can control when creating a post or page, and your site’s active permalink scheme. To change the format of URLs across your site you’d need to make a change either within your site admin, or to add code to a theme or plugin to manually override the permalink scheme. Beyond specifying the post slug there isn’t a formal way to control the entire permalink via the REST API.

Because this question touches on the functionality of the API itself and not this library _per se_, I’m going to close this issue as not applicable. Thank you for your question, and please let us know if there’s any problems you encounter while trying to use this library on your project!
